File.read!("./input.txt")
|> String.split("\n\n", trim: true)
|> Stream.map(&String.split(&1, "\n", trim: true))
|> Stream.map(&Enum.map(&1, fn s -> String.to_integer(s) end))
|> Stream.map(&Enum.sum/1)
|> Enum.to_list()
|> tap(&IO.inspect(Enum.max(&1)))
|> Enum.sort(:desc)
|> Enum.take(3)
|> Enum.sum()
|> IO.inspect()
